# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Game Developers Group @ IUPUI
tagline:          'A Jekyll theme'
description:      'A student group focused on both professional and hobby game developement! Join us Fridays in IT255 @ 6pm.'
#url:              http://www.indiana.edu/~gamedev
#baseurl:          http://www.indiana.edu/~gamedev/

url:              http://www.indiana.edu/~gamedev
baseurl:          http://www.indiana.edu/~gamedev/

author:
  name:           'Game Developers Group'
  url:            http://www.indiana.edu/~gamedev/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           
